version: "3.4"
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana.pem:/etc/certs/grafana.pem
      - ./config/grafana.key:/etc/certs/grafana.key
      - ./.data/grafana:/var/lib/grafana grafana/grafana
    # ports:
    #   - 9080:9080
    # networks:
    #   - monitoring
    network_mode: host

  victoria-metrics:
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    command: -storageDataPath=/victoria-metrics-data -memory.allowedPercent=20 -promscrape.config=/etc/victoria/prometheus.yml
    volumes:
      - ./.data/victoria:/victoria-metrics-data
      - ./config/prometheus.yml:/etc/victoria/prometheus.yml
    # ports:
    #   - 8428:8428
    # networks:
    #   - monitoring
    network_mode: host
    
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    # ports:
    #   - 9100:9100
    # networks:
    #   - monitoring
    network_mode: host

# networks:
#   monitoring:

volumes:
  grafana-data:
  victoria-data:
