global:
  scrape_interval: 30s

scrape_configs:
  - job_name: "victoria-metrics"
    scrape_interval: 30s
    static_configs:
    - targets: ["localhost:8428"]

  - job_name: "node"
    static_configs:
    - targets: ["localhost:9100"]
